[package]
name = "nanosat-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "nanosat"
path = "src/main.rs"

[dependencies]
nanosat = { path = "../nanosat" }
clap = { version = "4.5.37", features = ["derive"] }
